In [21]:
import pandas as pd

filename = "USCB_Ziemowit_catalog"
file_path = f"data/txt_files/{filename}.txt"

df = pd.read_csv(file_path, sep=r'\s+', names=['time', 'lat', 'long', 'depth', 'mag'])

df.head()

            time      lat     long  depth   mag
0  736786.014414  50.1226  19.2122      1  1.11
1  736786.163893  50.1225  19.2142      1  1.32
2  736786.176469  50.1151  19.1579      1  1.57
3  736786.274492  50.1240  19.2086      1  0.79
4  736786.336310  50.1144  19.1568      1  0.11

In [22]:
magnitude_threshold = 0.5

df_filtered = df[df['mag'] >= magnitude_threshold]

print(f"Rows before: {len(df)} | Rows after: {len(df_filtered)}")
df_filtered.head()

Rows before: 20017 | Rows after: 7508

            time      lat     long  depth   mag
0  736786.014414  50.1226  19.2122      1  1.11
1  736786.163893  50.1225  19.2142      1  1.32
2  736786.176469  50.1151  19.1579      1  1.57
3  736786.274492  50.1240  19.2086      1  0.79
5  736786.336571  50.1146  19.1574      1  0.79

In [24]:
clean_filename = "USCB_Ziemowit"
new_filename = f"{clean_filename}_MTR-{magnitude_threshold}.txt"
output_path = f"data/Ziemowit_txt/{new_filename}"

df_filtered.to_csv(output_path, sep=' ', header=False, index=False)

print(f"Filtered file successfully saved as: {output_path}")

Filtered file successfully saved as: data/Ziemowit_txt/USCB_Ziemowit_MTR-0.5.txt